### PR TITLE
Add deps.yml to help update dependencies from the CLI.

### PR DESCRIPTION
**Pull request by stuaxo**
The adds a deps.yml and info on running the deps cli tool to patch dependencies.
The first part of https://github.com/preshing/cairo-windows/issues/5

I've purposely put this branch one behind HEAD so you can run the tool and see it change the code to upgrade cairo etc to the current version.

The tools seems to be able to generate changes much like the PR you created to update freetype, cairo last time.
Try the tool and see what you think :)

### CODE REVIEW

**Comment by preshing** [comment]
Looks interesting! I didn't try running it yet but I believe that it does what you say it does 😄

**Comment by stuaxo** [comment]
I did put that note in for a reason - it seemed to stop working on my own branch, but carried on working on yours !

I'd been messing a lot with git on my own repo which may have confused it, but it was working up until about 5 minutes before I made the PR.

**Comment by preshing** [comment]
Any idea why it would work in one branch but not another?

**Comment by stuaxo** [comment]
I'm not sure at the moment, I sent a mail to Dave Gaeddert at dropseed helped get me setup and with the initial version of this.

I was messing with my git repo a *lot*, setting up remotes to this and my own PR, I also left a github workflow running every 15 minutes last night, so maybe I hit some kind of limit.

**Pull request merged**
